version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.16.0
    container_name: gitea_test
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /tmp/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
