version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.17.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=git.sliton.ru
    restart: always
    networks:
      - gitea
    volumes:
      - /storage0/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
